import type { Metadata } from "next";
import './globals.css';

import { Montserrat_Alternates } from 'next/font/google';

const montserrat = Montserrat_Alternates({
  weight: "500",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Valantis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
